version: '3.8'

services:
  adminer:
    build: .
    container_name: adminer-custom
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST:-localhost}
    restart: unless-stopped